// Generated by Dagger (https://google.github.io/dagger).
package oberescalator.di;

import android.content.Context;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import oberescalator.data.AppDatabase;
import javax.inject.Provider;

public final class AppModule_ProvideAppDatabaseFactory implements Factory<AppDatabase> {
  private final AppModule module;

  private final Provider<Context> contextProvider;

  public AppModule_ProvideAppDatabaseFactory(AppModule module, Provider<Context> contextProvider) {
    this.module = module;
    this.contextProvider = contextProvider;
  }

  @Override
  public AppDatabase get() {
    return provideInstance(module, contextProvider);
  }

  public static AppDatabase provideInstance(AppModule module, Provider<Context> contextProvider) {
    return proxyProvideAppDatabase(module, contextProvider.get());
  }

  public static AppModule_ProvideAppDatabaseFactory create(
      AppModule module, Provider<Context> contextProvider) {
    return new AppModule_ProvideAppDatabaseFactory(module, contextProvider);
  }

  public static AppDatabase proxyProvideAppDatabase(AppModule instance, Context context) {
    return Preconditions.checkNotNull(
        instance.provideAppDatabase(context),
        "Cannot return null from a non-@Nullable @Provides method");
  }
}
